version: "2"
linters:
  enable:
    - misspell
    - unconvert
    - unparam
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vitaliipsl/image-gen-mcp
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
